<h1>Create User</h1>

<form method="post" action="/learning_phalcon/public/users/store">

<p>
    Name:
    <input type="text" name="name" placeholder="Please Enter Your Name">
</p> 

<p>
    Email:
    <input type="text" name="email" placeholder="Please Enter Your Email">
</p>

<p>
    Number:
    <input type="int" name="number" placeholder="Ex: 9876543210">
</p>

<p>
    City:
    <input type="text" name="city" placeholder="Enter Your City">
</p>


<p>
    State:
    <select name="state" >
        <option value="">Select Your State</option>
        <option value="Andhra-pradesh">Andhra-pradesh</option>
        <option value="Bihar">Bihar</option>
        <option value="Chhattisgarh">Chhattisgarh</option>
        <option value="Goa">Goa</option>
        <option value="Gujarat">Gujarat</option>
        <option value="Karnataka">Karnataka</option>
        <option value="Odisa">Odisa</option>
        <option value="Uttar-Pradesh">Uttar-Pradesh</option>
        <option value="Uttarakhand">Uttarakhand</option>

    </select>
</p>

<p>
    Country:
    <select name="country" >
        <option value="">Select Your Country</option>
        <option value="India">India</option>
        <option value="USA">USA</option>
        <option value="Canada">Canada</option>
        <option value="Russia">Russia</option>
    </select>
</p>


<p>
    Pincode:
    <input type="text" name="pincode" placeholder="Enter Your Pincode">
</p>

<br>
<button type="submit">
    Save User
</button>
<br>

<h1>Please Enter Your Detail to Store in Database.</h2>
</form>