<h1>Create User</h1>

<form method="post" action="/learning_phalcon/public/users/store">

<p>
    Name:
    <input type="text" name="name" placeholder="Please Enter Your Name">
</p> 

<p>
    Email:
    <input type="text" name="email" placeholder="Please Enter Your Email">
</p>
<br>
<button type="submit">
    Save User
</button>
<br>

<h2>Please Enter Your Detail to Store in Database.</h2>
</form>