<h1>Edit User</h1>

<form method="POST"
      action="/learning_phalcon/public/users/update">

    <input type="hidden"
           name="id"
           value="<?= $user->id ?>">

    <p>
        Name:
        <input type="text"
               name="name"
               value="<?= $user->name ?>">
    </p>

    <p>
        Email:
        <input type="email"
               name="email"
               value="<?= $user->email ?>">
    </p>

    <p>
    Number:
    <input type="int" name="number" placeholder="Ex: 9876543210">
</p>

<p>
    City:
    <input type="text" name="city" placeholder="Enter Your City">
</p>


<p>
    State:
    <select name="state" >
        <option value="">Select Your State</option>
        <option value="Andhra-pradesh">Andhra-pradesh</option>
        <option value="Bihar">Bihar</option>
        <option value="Chhattisgarh">Chhattisgarh</option>
        <option value="Goa">Goa</option>
        <option value="Gujarat">Gujarat</option>
        <option value="Karnataka">Karnataka</option>
        <option value="Odisa">Odisa</option>
        <option value="Uttar-Pradesh">Uttar-Pradesh</option>
        <option value="Uttarakhand">Uttarakhand</option>

    </select>
</p>

<p>
    Country:
    <select name="country" >
        <option value="">Select Your Country</option>
        <option value="India">India</option>
        <option value="Use">USA</option>
        <option value="Canada">Canada</option>
        <option value="Russia">Russia</option>
    </select>
</p>


<p>
    Pincode:
    <input type="int" name="pincode" placeholder="Enter Your Pincode">
</p>

    <button type="submit">
        Update User
    </button>
<br>

<h2>Update Your Details...</h2>
</form>