<h1>Users List</h1>

<a href="/learning_phalcon/public/users/create">
    Create User
</a>

<br><br>

<table border="1" cellpadding="10">

    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Action</th>
    </tr>

    <?php foreach ($users as $user) { ?>

        <tr>

            <td><?= $user->id ?></td>

            <td><?= $user->name ?></td>

            <td><?= $user->email ?></td>

            <td>

                <a href="/learning_phalcon/public/users/edit/<?= $user->id ?>">
                    Edit
                </a>

                |

                <a href="/learning_phalcon/public/users/delete/<?= $user->id ?>"
                   onclick="return confirm('Are you sure?')">

                    Delete
                </a>

            </td>

        </tr>

    <?php } ?>

    <br>
    <h1>You Can see "Users"...</h1>

</table>